version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: rma
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '5432:5432'
    volumes:
      - rma-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - rma-redis:/var/lib/redis/data

  sidekiq:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: ./Dockerfile.rails
    command: bundle exec sidekiq
    env_file:
      - .env

  rma:
    depends_on:
      - postgres
      - redis
      - sidekiq
    build:
      context: .
      dockerfile: ./Dockerfile.rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8010 -b '0.0.0.0' -e ${RAILS_ENV}"
    volumes:
      - ./resource-management-api:/usr/src/app
    ports:
      - '8010:8010'
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - rma
    ports:
      - '8020:8020'

volumes:
  rma-postgres:
  rma-redis: